name: NerdNuCustomDrops
version: ${project.version}
main: nu.nerd.CustomDrops
description: Custom head drops for Nerd.Nu Minecraft server.
authors:
  - Mats1300
website: https://github.com/Mats1300/NerdNuCustomDrops
api-version: 1.21.8
load: STARTUP
license: MIT
softdepend:
  - Bolt
commands:
  mobhead:
    description: Manage mob heads (list or give).
    usage: /mobhead <list|give>
    permission: nerdnucustomdrops.mobhead
    aliases: [mh]

permissions:
  nerdnucustomdrops.mobhead:
    description: Allows use of the /mobhead command.
    default: true
  nerdnucustomdrops.mobhead.list:
    description: Allows listing available mob heads.
    default: true
  nerdnucustomdrops.mobhead.give:
    description: Allows giving mob heads to players.
    default: op