name: NerdNuCustomDrops
version: ${project.version}
main: nu.nerd.CustomDrops
description: Custom head drops for Nerd.Nu Minecraft server.
authors:
  - Mats1300
website: https://github.com/Mats1300/NerdNuCustomDrops
api-version: 1.21.8
load: STARTUP
license: MIT
softdepend:
  - Bolt
commands:
  mobhead:
    description: List all available mob heads.
    usage: /mobhead list
    permission: mobhead.list